name: Python application

on:
  push: 
   branches: main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Rsync Deployer
        uses: imajeetyadav/rsync-deployer@1.0.0
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER_NAME }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE_PATH: "."
          TARGET_PATH: "/home/ubuntu"
          PORT: 22
          RSYNC_PARAMETERS: "" 
          DELETE_OPTION: "false"
          EXCLUDE_LIST: ".git, .github"
          DRY_RUN: "false"

      - name: Post Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            sudo systemctl restart fastapi
